spec:
  template:
    spec:
      containers:
        - readinessProbe:
            httpGet:
              path: /api/greeting
              port: 8080
              scheme: HTTP
          livenessProbe:
            httpGet:
              path: /api/greeting
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 30
          resources:
          limits:
            cpu: 200m
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 100Mi
